CREATE DATABASE QLSVDN
GO

USE QLSVDN
GO

CREATE TABLE KHOA
(
MaKhoa char(4),
TenKhoa nvarchar(100),
CONSTRAINT PK_MAKHOA PRIMARY KEY (MaKhoa)
)
GO

CREATE TABLE LOP
(
MaLop char(4),
TenLop nvarchar(100),
MaKhoa char(4),
CONSTRAINT PK_MALOP PRIMARY KEY(MaLop),
CONSTRAINT FK_KHOA_MAKHOA FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa)
)
GO

CREATE TABLE SINHVIEN
(
MaSinhVien char(8),
HoTen nvarchar(100),
NgaySinh Date,
MaLop char(4),
CONSTRAINT PK_MASINHVIEN PRIMARY KEY(MaSinhVien),
CONSTRAINT FK_LOP_MALOP FOREIGN KEY (MaLop) REFERENCES LOP(MaLop)
)
GO

CREATE TABLE MONHOC
(
MaMonHoc char(10),
TenMonHoc nvarchar(100),
CONSTRAINT PK_MAMONHOC PRIMARY KEY(MaMonHoc)
)
GO

CREATE TABLE DIEM
(
MaSinhVien char(8),
MaMonHoc char(10),
Diem float,
CONSTRAINT PK_MASINHVIEN_MaMonHoc PRIMARY KEY(MaSinhVien, MaMonHoc)
)